services:
  dcr:
    build:
      context: .  
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: root
