services:
  dcr:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
